### ISSUE TITLE
Not seeing headphones

### ISSUE THREAD

**Issue by Solkos** [ChaosinaCan/AudioPipe#5]
I have Corsair Void Pro Wireless headphones and sadly they don't show up on the Audio Redirect list.  It only says "use default device".  It doesn't appear to be re-directing my sound?  Unsure.

**Comment by Solkos** [comment]
I enable my other speakers and they all show up.  Just not the wireless headphones.

**Comment by joelspadin** [comment]
Are your headphones set as Windows' default playback device? Audio Redirect can only redirect from your default device to a different one, so if you want to redirect to your headphones, you'll have to make something else be the default first. (If I actually let you redirect a device to itself, it would probably sound a bit like the start of this video: https://www.youtube.com/watch?v=rNIQLMXsoJA)

If that's not it, right click the speaker icon on your taskbar and select **Playback devices**. Select your headphones and open its properties. It should look like this:

![image](https://user-images.githubusercontent.com/760836/36516114-26f6c6ba-1742-11e8-9523-61d6a94f1c03.png)

What does it say under the **Controller Information** section? If it says "Generic USB Audio", it should show up in Audio Redirect. If it says something else, that might help track down why it won't show up.

**Comment by Solkos** [comment]
AH!  That worked!

**Comment by Solkos** [comment]
thank you!

**Comment by joelspadin** [comment]
Great! You're welcome.

**Comment by joelspadin** [comment]
Added #6 to try to improve the UI around the default device.
